In [4]:
#rank 0 tensor (scalars)
import numpy as np
rank0 = np.array(2)
print(rank0,rank0.shape,rank0.ndim,rank0.dtype)


2 () 0 int64


In [3]:
#rank 1 tensor(vectors)
rank1 = np.array([1,2,3])
print(rank1,rank1.shape,rank1.ndim,rank1.dtype)

[1 2 3] (3,) 1 int64


In [6]:
#rank 2 tensor(vectors)
rank2 = np.array([[1,2,3],[4,5,6]])
print(rank2,rank2.shape,rank2.ndim,rank2.dtype)

[[1 2 3]
 [4 5 6]] (2, 3) 2 int64


In [8]:
#access specific element from 2d matrix
print(rank2[1][2])

6


In [10]:
#rank 3 tensor (3D matrix)
rank3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(rank3,rank3.shape,rank3.ndim,rank3.dtype)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] (2, 2, 3) 3 int64


In [11]:
print(rank3[0][0][1])
print(rank3[0][1][1])
print(rank3[0][1][1])

2
5
5


In [12]:
'''Applying operations 
      ones, zeros, fill, eye, identity '''
#ones with default float representation
ones = np.ones([4,5])
print(ones)

#ones with integer representation
ones = np.ones([4,5], dtype = int)
print(ones)

#zeros
zeros = np.zeros([2,3,3])
print(zeros)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [25]:
full1= np.full([5,4],2)
print(full1)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [17]:
eyes=np.eye(4,4)
print(eyes)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [23]:
iden=np.identity(4)
print(iden)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [29]:
import tensorflow as tf 
#scalar 
scalar = tf.constant(3)
print(scalar)
scalar = tf.Variable(3)
print(scalar)

#vector
vector = tf.constant([1,2])
print(vector)

#2D matrix
matrix2d = tf.constant([[1,2],[4,5]])
print(matrix2d)

#ones
ones = tf.ones([3,2])
print(ones)
#zeros
zeros = tf.zeros([4,4])
print(zeros)
#fill
fill = tf.fill([4,4],4)
print(fill)

tf.Tensor(3, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]], shape=(4, 4), dtype=int32)
